# Generated by Django 5.2.5 on 2025-08-26 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=120)),
                ("auteur", models.CharField(max_length=120)),
                ("titre", models.CharField(max_length=200)),
                (
                    "note",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("disponibilite", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                ("prenom", models.CharField(max_length=120)),
                ("age", models.PositiveIntegerField()),
                ("lieu_residence", models.CharField(max_length=120)),
                (
                    "livre_emprunte",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emprunteur",
                        to="gestion.livre",
                    ),
                ),
            ],
        ),
    ]
